## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [0]:
import os
import numpy as np
import pandas as pd

In [0]:
# 設定 data_path
dir_data = './data/'

In [9]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [12]:
(row_count, column_count) = app_train.shape
row_count, column_count

(307511, 122)

#### 列出所有欄位

In [20]:
for col in app_train.columns: 
    print(col)

SK_ID_CURR
TARGET
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
OWN_CAR_AGE
FLAG_MOBIL
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
EXT_SOURCE_1
EXT_SOURCE_2
EXT_SOURCE_3
APARTMENTS_AVG
BASEMENTAREA_AVG
YEARS_BEGINEXPLUATATION_AVG
YEARS_BUILD_AVG
COMMONAREA_AVG
ELEVATORS_AVG
ENTRANCES_AVG
FLOORSMAX_AVG
FLOORSMIN_AVG
LANDAREA_AVG
LIVINGAPARTMENTS_AVG
LIVINGAREA_AVG
NONLIVINGAPARTMENTS_AVG
NONLIVINGAREA_AVG
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
YEARS_BUILD_MODE
COMMONAREA_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
FLOORSMIN_MODE
LANDAREA_MODE
LIVINGAPARTMENTS_MODE
LIVINGAREA_MODE
NONLIVINGAPARTMENTS_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
YEARS_BUILD_MEDI
COMMONAREA_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
FLOORSMIN_MEDI
LANDAREA_MEDI
LIVINGAPARTMENTS_MEDI
LIVINGAREA_MEDI
NONLIVINGAPARTMENTS_MEDI
NONLIVINGAREA_MEDI
FONDKAPREMONT_MODE
HOUSETYPE_MODE
TOTALAREA_MODE
WALLSMATERIAL_MODE
EMERGENCYSTATE_MODE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
FLAG_DOCUMENT_2
FLAG_DOCUMENT_3
FLAG_DOCUMENT_4
FLAG_DOCUMENT_5
FLAG_DOCUMENT_6
FLAG_DOCUMENT_7
FLAG_DOCUMENT_8
FLAG_DOCUMENT_9
FLAG_DOCUMENT_10
FLAG_DOCUMENT_11
FLAG_DOCUMENT_12
FLAG_DOCUMENT_13
FLAG_DOCUMENT_14
FLAG_DOCUMENT_15
FLAG_DOCUMENT_16
FLAG_DOCUMENT_17
FLAG_DOCUMENT_18
FLAG_DOCUMENT_19
FLAG_DOCUMENT_20
FLAG_DOCUMENT_21
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [21]:
# 以 column name 取出單行成 Series
app_train.loc[:, 'NAME_CONTRACT_TYPE']

0              Cash loans
1              Cash loans
2         Revolving loans
3              Cash loans
4              Cash loans
5              Cash loans
6              Cash loans
7              Cash loans
8              Cash loans
9         Revolving loans
10             Cash loans
11             Cash loans
12             Cash loans
13             Cash loans
14             Cash loans
15             Cash loans
16             Cash loans
17        Revolving loans
18        Revolving loans
19             Cash loans
20        Revolving loans
21             Cash loans
22             Cash loans
23             Cash loans
24             Cash loans
25             Cash loans
26             Cash loans
27             Cash loans
28             Cash loans
29        Revolving loans
               ...
307481         Cash loans
307482         Cash loans
307483         Cash loans
307484         Cash loans
307485    Revolving loans
307486         Cash loans
307487         Cash loans
307488         Cash loans
307489         Cash loans
307490         Cash loans
307491         Cash loans
307492         Cash loans
307493         Cash loans
307494         Cash loans
307495         Cash loans
307496    Revolving loans
307497         Cash loans
307498         Cash loans
307499         Cash loans
307500         Cash loans
307501         Cash loans
307502         Cash loans
307503         Cash loans
307504         Cash loans
307505         Cash loans
307506         Cash loans
307507         Cash loans
307508         Cash loans
307509         Cash loans
307510         Cash loans
Name: NAME_CONTRACT_TYPE, Length: 307511, dtype: object

In [23]:
# 以 column name 取出多行成 DF
app_train.loc[:, 'NAME_CONTRACT_TYPE':'CODE_GENDER']

       NAME_CONTRACT_TYPE CODE_GENDER
0              Cash loans           M
1              Cash loans           F
2         Revolving loans           M
3              Cash loans           F
4              Cash loans           M
5              Cash loans           M
6              Cash loans           F
7              Cash loans           M
8              Cash loans           F
9         Revolving loans           M
10             Cash loans           F
11             Cash loans           F
12             Cash loans           F
13             Cash loans           M
14             Cash loans           F
15             Cash loans           M
16             Cash loans           M
17        Revolving loans           F
18        Revolving loans           F
19             Cash loans           F
20        Revolving loans           M
21             Cash loans           F
22             Cash loans           F
23             Cash loans           F
24             Cash loans           M
25             Cash loans           F
26             Cash loans           F
27             Cash loans           M
28             Cash loans           M
29        Revolving loans           M
...                   ...         ...
307481         Cash loans           M
307482         Cash loans           F
307483         Cash loans           F
307484         Cash loans           F
307485    Revolving loans           F
307486         Cash loans           F
307487         Cash loans           M
307488         Cash loans           F
307489         Cash loans           F
307490         Cash loans           M
307491         Cash loans           M
307492         Cash loans           M
307493         Cash loans           F
307494         Cash loans           M
307495         Cash loans           M
307496    Revolving loans           F
307497         Cash loans           F
307498         Cash loans           M
307499         Cash loans           F
307500         Cash loans           F
307501         Cash loans           F
307502         Cash loans           F
307503         Cash loans           F
307504         Cash loans           F
307505         Cash loans           F
307506         Cash loans           M
307507         Cash loans           F
307508         Cash loans           F
307509         Cash loans           F
307510         Cash loans           F

[307511 rows x 2 columns]

In [24]:
# 以 index number 取出單行成 Series
app_train.iloc[:, 2]

0              Cash loans
1              Cash loans
2         Revolving loans
3              Cash loans
4              Cash loans
5              Cash loans
6              Cash loans
7              Cash loans
8              Cash loans
9         Revolving loans
10             Cash loans
11             Cash loans
12             Cash loans
13             Cash loans
14             Cash loans
15             Cash loans
16             Cash loans
17        Revolving loans
18        Revolving loans
19             Cash loans
20        Revolving loans
21             Cash loans
22             Cash loans
23             Cash loans
24             Cash loans
25             Cash loans
26             Cash loans
27             Cash loans
28             Cash loans
29        Revolving loans
               ...
307481         Cash loans
307482         Cash loans
307483         Cash loans
307484         Cash loans
307485    Revolving loans
307486         Cash loans
307487         Cash loans
307488         Cash loans
307489         Cash loans
307490         Cash loans
307491         Cash loans
307492         Cash loans
307493         Cash loans
307494         Cash loans
307495         Cash loans
307496    Revolving loans
307497         Cash loans
307498         Cash loans
307499         Cash loans
307500         Cash loans
307501         Cash loans
307502         Cash loans
307503         Cash loans
307504         Cash loans
307505         Cash loans
307506         Cash loans
307507         Cash loans
307508         Cash loans
307509         Cash loans
307510         Cash loans
Name: NAME_CONTRACT_TYPE, Length: 307511, dtype: object

In [26]:
# 以 index number 取出多行成 DF
app_train.iloc[:, [2,3]] # = app_train.iloc[:, 2:3]

       NAME_CONTRACT_TYPE CODE_GENDER
0              Cash loans           M
1              Cash loans           F
2         Revolving loans           M
3              Cash loans           F
4              Cash loans           M
5              Cash loans           M
6              Cash loans           F
7              Cash loans           M
8              Cash loans           F
9         Revolving loans           M
10             Cash loans           F
11             Cash loans           F
12             Cash loans           F
13             Cash loans           M
14             Cash loans           F
15             Cash loans           M
16             Cash loans           M
17        Revolving loans           F
18        Revolving loans           F
19             Cash loans           F
20        Revolving loans           M
21             Cash loans           F
22             Cash loans           F
23             Cash loans           F
24             Cash loans           M
25             Cash loans           F
26             Cash loans           F
27             Cash loans           M
28             Cash loans           M
29        Revolving loans           M
...                   ...         ...
307481         Cash loans           M
307482         Cash loans           F
307483         Cash loans           F
307484         Cash loans           F
307485    Revolving loans           F
307486         Cash loans           F
307487         Cash loans           M
307488         Cash loans           F
307489         Cash loans           F
307490         Cash loans           M
307491         Cash loans           M
307492         Cash loans           M
307493         Cash loans           F
307494         Cash loans           M
307495         Cash loans           M
307496    Revolving loans           F
307497         Cash loans           F
307498         Cash loans           M
307499         Cash loans           F
307500         Cash loans           F
307501         Cash loans           F
307502         Cash loans           F
307503         Cash loans           F
307504         Cash loans           F
307505         Cash loans           F
307506         Cash loans           M
307507         Cash loans           F
307508         Cash loans           F
307509         Cash loans           F
307510         Cash loans           F

[307511 rows x 2 columns]